### ISSUE TITLE
'latest' docker image seems not to be the latest

### ISSUE THREAD

**Issue by frydrycht** [tus/tusd#1116]
**Describe the bug**
I am working on `pre-create` hook to add some ID prefix to separate the data in file storage. I found that I can use slashes to build hierarchical (directory-like) schema. It was introduced with PR https://github.com/tus/tusd/pull/1020 and finally released in version [2.3.0](https://github.com/tus/tusd/compare/v2.2.2...v2.3.0). I used the `latest` version of docker image but I got 404 on `PATCH` request to upload file content. After some time I decided to change docker image first to `v2.3.0` and it started to work. Then I verified `v2.4.0` (latest release) and it also works so it seems `latest` docker image does not contain latest version of tusd.

**To Reproduce**
1. Use `latest` docker image to start the service
2. Create `pre-create` hook to change the file ID to contain prefix with slash (/)
3. You cannot upload the file as there is no driectory for prefix and if directory exists then `PATCH` request to upload the content ends with 404

**Expected behavior**
`latest` docker image contains latest version of tusd

**Setup details**
N.A.

**Comment by Acconut** [comment]
That's odd. Looking at the [tags for the Docker image](https://hub.docker.com/r/tusproject/tusd/tags) confirms that the latest tag was created at the same time as the 2.4.0 tag. So that checks out.

When pulling the latest tag, I also get 2.4.0 as expected:

```
$ docker run --rm tusproject/tusd:latest --version
Version: v2.4.0
Commit: 50b9ff5623c26c856ec97e2e0a9a44c0f6baaceb
Date: Mon Mar 18 20:42:00 UTC 2024
```

Do you get something different? Maybe the lastest tag is cached for you and you have to pull it again?
