### ISSUE TITLE
Is lockUpload really needed for HEAD? 

### ISSUE THREAD

**Issue by jimydavis** [tus/tusd#1161]
I had a situation where the uppy javascript client called `PATCH` and `HEAD` at the same time. I am not very sure but it looks like https://github.com/tus/tusd/blob/585d7a57110a544809fab98c683cdf7331b8e52a/pkg/handler/unrouted_handler.go#L1352 is called by both HEAD and PATCH. 

Due to HEAD and PATCH being called at the same time from frontend, the HEAD succeeded but the PATCH got "interrupted" error. Since HEAD is theoretically non-write, why does HEAD lead to this locking?

Maybe I understood the whole code path wrong. Thanks for the help!

**Comment by Acconut** [comment]
Yes, acquiring the lock is also needed for HEAD requests because read access to a resource that is concurrently modified is not safe. It's not relevant that HEAD is not modifying the resource. But without the lock, it might retrieve an invalid state about the upload. Maybe the documentation can help you understand this in more detail: https://tus.github.io/tusd/advanced-topics/locks/

> Due to HEAD and PATCH being called at the same time from frontend

I would recommend to not send HEAD requests during the upload. This shouldn't be necessary.

**Comment by Acconut** [comment]
Please open an issue in the Uppy repository about this and include your code. Please be as detailed as you can and mention ways to reproduce this.

> At first I thought the `onProgress` flag (that updates a progress bar) calls HEAD but it seems like that is done client side and no HEAD is sent out.

Correct. Progress updates are retrieved without the use of HEAD. HEAD is only used for resuming uploads, so I assume you are accidentally triggering resumption while the upload is still running.

**Comment by Acconut** [comment]
> I found out that the true error underneath was that the file size (`Upload-Length`) was X but upon calling HEAD, the response from server for `Upload-Offset` was greater than X

That is very odd and should never happen. Please let us know if you encounter this problem again!
