### ISSUE TITLE
Possibility of race: post-create vs post-receive?

### ISSUE THREAD

**Issue by geor-g** [tus/tusd#1174]
Hi,

To keep potential races out of my setup: is there currently any guarantee in place, that the `post-create` hook is called before the first invocation of the `post-receive` hook, if relying on a configuration like `-progress-hooks-interval=30s`?

I guess there isn't, as the docs tell:

> During the lifecycle of an upload, multiple hooks may be triggered. Their execution can happen concurrently and in general the order of hooks is not guaranteed.

Further guessing from my side: the 30s as mentioned above might help potentially, but still, if shit hits the fan, `post-receive` might be executed (instead of invoked?) before `post-create`?

Thanks a lot for all the work you do!

**Comment by Acconut** [comment]
> s there currently any guarantee in place, that the `post-create` hook is called before the first invocation of the `post-receive` hook

No, all guarantees are listed in https://tus.github.io/tusd/advanced-topics/hooks/#list-of-available-hooks:

> The only guarantees are that pre-create will always be the first hook for any upload and that post-finish is started after pre-finish has been completed.

You should expect that post-received is emitted at any moment (but after pre-create is finished), including post-create in rate circumstances. This can especially happen if you using HTTP hooks and requests are retried.

> relying on a configuration like `-progress-hooks-interval=30s`

That also won't always work because `post-receive` is also emitted when a PATCH request ends. If a PATCH requests takes 5s, post-receive is emitted after 5s. If it takes 35s, post-recevie is emitted after 30s and then 35s again.

In general, I recommend you to design your hooks to be independent of any order and fill in missing state (e.g. missing database entries) on their own.

**Comment by geor-g** [comment]
Thanks for your quick response, and thanks for the confirmation, it was my (partial) understanding as well.
