### ISSUE TITLE
the .info files generated by tusd may contain sensible information !

### ISSUE THREAD

**Issue by johnypowaa** [tus/tusd#131]
Dear all,

You recommend to use the 'pre-create' hook to check a tus.io client for authentication and authorization.
And you recommend to use 'MetaData' for this.

And this works actually great, but the problem is that my client credentials get stored in clear text in an .info files next to the .bin file on the server.

```
For example:
{"ID":"64d6dfce21ed983d707dfdcd5f365b2f","Size":11362307,"Offset":0,"MetaData":{"filename":"upload.7z","myPasswordKey":"myPasswordValue"},"IsPartial":false,"IsFinal":false,"PartialUploads":null}
```

This is a big security issue.

They are many ways you could solve this issue.

Best regards and thanks in advance.

**Comment by Acconut** [comment]
I agree that this is a problem but IMO this should rather be solved on your end. For example, instead of transmitting the password value, you could use a one-time token which is valid for exactly one upload creation and can therefore not be reused latter. What do you think?

> They are many ways you could solve this issue.

Out of curiosity, what would your preferred way be?

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)
