### ISSUE TITLE
AWS S3 ListParts API call returns max 1000 parts

### ISSUE THREAD

**Issue by koenvo** [tus/tusd#147]
**problem**
The ListParts API of S3 returns at most 1000 parts in a single call. Together with the MaxPartSize (hardcoded) of 6MB the maximum file size that I can upload to s3 is 6GB. When the "limit" of 1000 parts is reached the GetInfo method will return incorrect information causing ErrMismatchOffset errors.

**possible solution**
The ListParts call should be done in a loop and do additional calls while IsTruncated is set.  I'm willing to create a PR for this, altho I never coded in go before. Let's see :-)
It would also be nice to be able to change MaxPartSize. Is there a reason why 6MB is chosen?

Does anyone know a temporary solution? I prefer not build tusd from source.

**Comment by trickkiste** [comment]
Hi @koenvo, I just ran into the exact same problem. Most of my uploads will be larger than 6GB, so this is crucial for me too.

According to http://docs.aws.amazon.com/AmazonS3/latest/dev/qfacts.html there is a hard limit of 10.000 parts in AWS S3 with 1000 max-parts per list request, as you described above.

I am wondering, how far you got in your investigation. I have just had a quick look at tusd code concerning that matter, but I presume the parts > 1000 are actually created but are not included in the s3.CompleteMultipartUploadInput response. Or do thing go wrong even earlier, e.g. do the parts uploaded past number 1000 receive the wrong content due to incorrect offset calculation.

My insights into the matter are still incomplete, I just sat down to investigate myself, but I wanted you to know, that I will also be working to resolve this and am hoping, that we can collaborate on this.

When you are reading this, please try to contact me in Slack, so we can coordinate our efforts.

My best regards,
Markus

**Comment by koenvo** [comment]
hi @trickkiste,

Thanks for your message. I managed to create some go code including tests. Please have a look at PR #148 . 

Due to the hard limit of 10.000 parts the files are now limited to 60GB. In my case this would be enough. Another change could be to make the MaxPartSize configurable but I didn't look into this yet.

[slack-noob]where can i find you at slack?[/slack-noob]

Kind regard,
Koen

**Comment by trickkiste** [comment]
Also, it seems to me, that having 
> MaxPartSize: 6 * 1024 * 1024,
> MinPartSize: 5 * 1024 * 1024,

hardcoded will not work for many large file scenarios, even if the 1000 max-parts limit for the s3.ListPartsInput response is dealt with correctly. 

http://docs.aws.amazon.com/AmazonS3/latest/dev/qfacts.html states
> Maximum object size | 5 TB
> Maximum number of parts per upload | 10,000
> Part size | 5 MB to 5 GB, last part can be < 5 MB

The maximum file size with 10,000 possible parts would be 60 GB with the current settings. Therfore it makes the most sense to me to actually calculate the optimal part-size based on these values and follow through with the patch suggested by @koenvo, which would loop through all truncated responses until it has received all parts.

**Comment by koenvo** [comment]
The calculated MaxPartSize sounds like a great idea. Do you have a suggestion for the calculation? 

The calculation should somehow take the size of the chunk sent by the client into account. In the current implementatie it's possible `MinPartSize - 1` bytes are dropped. When a client sends chunks of `MaxPartSize + MinPartSize - 1` bytes almost of 45% of the data is dropped and a lot bandwidth is wasted.

Besides that a Part will never be smaller than a chunk sent by the client. So I think `MaxPartSize` should equal length of bytes in request

**Comment by trickkiste** [comment]
I have had a quick look at your patch and will play around with it next. What I saw yet was, that you might want to use the ListPartsPages function in the S3 sdk-for-go. It does the iterating through truncated requests for you.

I am user @flaneur in Slack. You need to "subscribe" to transloadit.slack.com.

**Comment by trickkiste** [comment]
@koenvo I tried to do it with ListPartsPages, but it creates a testing nightmare, as it can not be mocked properly.

**Comment by Acconut** [comment]
Thank you for your investigations, I wasn't available to last days so I could not comment here but that's over now.

>  Is there a reason why 6MB is chosen?

The thought behind this number is that it should be small enough that it would not hurt if a chunk of 6MB must be reuploaded from the tus client again. Here's the reason: If tusd fails to upload the chunk to S3 as a new part, the entire PATCH request is aborted, so the client must reupload all the data which is lost. However, it's debatable whether 6MB is the current number for this, mostly because it depends on the uplink speed. In fact, I am very open to increase this number.

> Due to the hard limit of 10.000 parts the files are now limited to 60GB. In my case this would be enough. Another change could be to make the MaxPartSize configurable but I didn't look into this yet.

> Therfore it makes the most sense to me to actually calculate the optimal part-size based on these values

> I also think the above should go in a separate issue/PR or rename current issue + PR, because it's more than taking truncated responses into account.

I am happy to discuss possible solution for this in #149 to avoid confusion here.

Finally, I am going to close this in favour of #147 since we all agree that @koenvo has a good solution for it :)

Instead
