### ISSUE TITLE
Feature Request: Etcd Locker

### ISSUE THREAD

**Issue by thedrow** [tus/tusd#157]
It should be easy to implement an Etcd locker for tusd using https://github.com/Scalingo/go-etcd-lock
It will be useful in environments where Etcd is already present such as Kubernetes.

**Comment by Acconut** [comment]
I agree with you that this would be a nice addition to tusd and I am very happy to provide help for this and accept a PR. :)

Regarding the package you linked, I am a bit hesitant. It has no documentation and I am also not sure what value the time-to-live parameter (https://godoc.org/github.com/Scalingo/go-etcd-lock/lock#EtcdLocker.Acquire) should have, since the duration of an upload is not known before.

**Comment by thedrow** [comment]
I guess we could do it ourselves.

**Comment by kvz** [comment]
> It will be useful in environments where Etcd is already present such as Kubernetes.

'People' recommend about re-using etcd that k8s uses for internal management. That said, it's easy to run your own etcd using the coreos operator for it. A bit offtopic but thought i'd mention. 

As for supporting multiple locking mechanisms.. Would it be bad/too slow to shell out to acquire a lock? Most of these systems allow you to obtain locks on the command line, and then i suppose it would become rather easy to support many of them, or roll your own by just specifying which command is to be ran to acquire/check/release the lock.

**Comment by thedrow** [comment]
@kvz I don't think it is necessary to shell out. The go-etcd-lock package is just a helper. The API is simple enough.

**Comment by Acconut** [comment]
> As for supporting multiple locking mechanisms.. Would it be bad/too slow to shell out to acquire a lock? 

That's actually a nice idea. I believe, if you run tusd at large scale, this will become a performance issue since for nearly every request two commands must be executed. On the other hand, it's a very flexible solution. Do you know whether there is a command to obtain a lock for etcd?

> The API is simple enough.

Yes, but it still adds code which has to be maintained and tested. However, I am not sure which approach is better...

**Comment by kvz** [comment]
A counter argument to my own idea of shelling out, is people running tusd on container platforms. They will care about having single containerized processes so that there’s no risk of zombie or otherwise out of control processes unsupervised by the container health checks.

I believe this is why Vimeo wanted http hooks alongside of hooks shelling out. It’s possible this also becomes an issue (or rather, less than ideal situation) for Transloadit as we move onto k8s.

Haven’t really made my mind up but only just thought of this angle and thought I’d share :)

**Comment by Acconut** [comment]
I am basically open for both solutions, and are happy to accept a PR for this :)
