### ISSUE TITLE
Get user that does the upload when using tusd embedded in your Go app

### ISSUE THREAD

**Issue by gosom** [tus/tusd#184]
I embedded tusd into an existing web server and added the necessary endpoints
using
```
a.Router.HandleFunc("/event/upload", a.UploadHandler.PostFile).Methods("POST")
```
where UploadHander is an UnroutedHandler 

As you see this calls the PostFile method (https://sourcegraph.com/github.com/tus/tusd/-/blob/unrouted_handler.go#L220)

There is also a goroutine that listens to the channels as you see below.

```
func (a *App) setupPostHooks() {
	go func() {
		for {
			select {
			case info := <-a.UploadHandler.CompleteUploads:
				log.Println("COMPLETE ", info) // I would like to know the user who uploaded here
			case info := <-a.UploadHandler.TerminatedUploads:
				log.Println("TERMINATA ", info)
			case info := <-a.UploadHandler.UploadProgress:
				log.Println("PROGR ", info)
			case info := <-a.UploadHandler.CreatedUploads:
				log.Println("CREATE ", info)
			}
		}
	}()
}
```

Before the requests goes to the PostFile method I have a middleware that performs authentication using JWT tokens. There I set a user id in the request context.

The question is now how I can access that user id in the Fileinfo structs above when one of the above events happen?

I am thinking to write my own PostFile and add this to the FileInfo.Metadata .
Do you know another way?

**Comment by Acconut** [comment]
Your idea using metadata is near my recommendation: When the user starts the upload, you add the JWT token to the upload's metadata (see https://tus.io/protocols/resumable-upload.html#upload-metadata). How exactly you can pull this off depends on what tus client you are using (for example, tus-js-client has a `metadata` option). Whenever the hooks are fired, you can obtain the JWT token by accessing the metadata as `info.MetaData["JWTToken"]`.

**Comment by gosom** [comment]
This is how I did it, but I don't like it since the JWT token is also on the request Headers when user initially uses the upload endpoint (which uses PostFile). So , it would be nice that we could "override" the PostFile and add the JWT token behind the scenes to the FileInfo so the client does not have to do that.

**Comment by vith** [comment]
I think the whole `http.Request` should be available when handling these events. Besides the `.Header`, the `.RemoteAddr` field is also important.

As it is, I am going to have to smuggle the `RemoteAddr` into the `Upload-Metadata` header before calling `PostFile`, but even doing that is awkward since the `parseMeta` and `serializeMeta` functions are unexported: https://github.com/tus/tusd/blob/0.10.0/unrouted_handler.go#L835-L879

**Comment by Acconut** [comment]
We currently do not expose any details of the underlying HTTP request to hooks or the data store because we want the tus protocol to be an abstraction layer where consumers do not have to care about HTTP. In this thought, authorization or any other details should be carried in the upload's metadata. However, I realize that this is not intuitive and a annoyance for some users. Therefore, I am open to rethink this idea but let's discuss this in a separate issue: https://github.com/tus/tusd/issues/185
