### ISSUE TITLE
Pass all HTTP request headers to hooks

### ISSUE THREAD

**Issue by miladz68** [tus/tusd#185]
Suggestion:
It would be a vey nice feautre to pass all request headers in the hooks so they can be used to authorized uploads and downloads.

**Comment by Acconut** [comment]
As many people have asked about this feature, we are currently open to add this functionality.

**Comment by vith** [comment]
Carrying on from https://github.com/tus/tusd/issues/184#issuecomment-388109821

For things like logging, authorization, and authentication it would be helpful to have a way to access the `http.Request` in the context of the tus event/hook or vice versa.

When using tusd as a library, even if you wrap the handler method to access the request, it's difficult to associate that request with the upload ID generated by PostFile, for example.

**Comment by miladz68** [comment]
I will try to take a look at the source code and make a PR if it is OK.

**Comment by ljufa** [comment]
I also need access to headers in request in hook. Metadata approach will work if client has all data needed, which is not always the case.
In my case there is js-client that does not have access to jwt token but 'access token'. In hook I need to call oauth service to resolve jwt by access token, then call other service using jwt token.

Only not sure does it have to be limited to webhooks only?

**Comment by sagikazarmark** [comment]
Instead of passing every header to the hooks, how about making authorization an extension of the core protocol?

Either by using the `Authorization` header or by introducing an `Upload-Authorization` header.

I know that metadata can be used for this purpose, but introducing it as an extension allows custom implementations to verify a JWT token for example on its own, instead of waiting for a pre-create hook.

**Comment by Acconut** [comment]
> Instead of passing every header to the hooks, how about making authorization an extension of the core protocol?

That would also be a possible way but I also see other possibilities in passing request headers. For example, you may examine the `Host` header to see which server the user is uploading to and then make different decisions based on this.

> I know that metadata can be used for this purpose, but introducing it as an extension allows custom implementations to verify a JWT token for example on its own, instead of waiting for a pre-create hook.

I agree that authentication can be done using metadata and in most cases it's the approach I recommend. However, there are two issues with it:

The metadata values (and possible authentication details) can be read by anyone who can send a HEAD request to the upload URL. If this is not acceptable to you, you need to utilize single-use token for creating uploads which is a non-trivial task.

Furthermore, you would like to minimize the changes necessary to your front-end when adding tus uploads. If you already have a middleware to add authentication details to HTTP requests, you would like to reuse this functionality which is currently not easily possible.

**Comment by sagikazarmark** [comment]
> That would also be a possible way but I also see other possibilities in passing request headers. For example, you may examine the `Host` header to see which server the user is uploading to and then make different decisions based on this.

IMHO Authentication is special enough to not handle it the same way as headers.

> I agree that authentication can be done using metadata and in most cases it's the approach I recommend.

I tried to argue that it made sense NOT to use metadata for authentication.

TBH I'm not sure your position on this. 😄

**Comment by Acconut** [comment]
> TBH I'm not sure what your position is on this.

What I am trying to say is that this is not an easy question. There are situations where handling authentication over metadata is absolutely fine and there are other cases where you should not do it. Making a general statement about this is nearly impossible and it has to be decided on a for each case independently. I hope this makes sense :)

**Comment by ljufa** [comment]
> Would you be able to put the access token into the metadata and then resolve it for a JWT token inside the hook? The JS client has to access to it, so it should work.

Sure, but that would require additional code on client and hook side.
In my case tusd and other http services are behind authentication gateway/proxy that resolve and injects jwt token into headers. 

Is there any drawback of making request headers available in the hook?

**Comment by ljufa** [comment]
> No, this feature would not bee limited to HTTP hooks.

Cool, issue title made me think that :)

**Comment by Acconut** [comment]
> Is there any drawback of making request headers available in the hook?

No, but it's a solution that works right now without modifying tusd's source code.

> Cool, issue title made me think that :)

Thanks for pointing out, I will change the title.

**Comment by dantman** [comment]
I want/need this feature as well. I use JWT tokens for auth and if I do auth for uploads by passing the token in metadata instead of an Authorization header that means that the user's auth token will be stored in the `.info` file in the s3 bucket I have tusd upload to. The bucket is not publicly readable, but still I don't think it's a good idea to be persistently storing the user's auth token. Anyone who gains simple read access to a s3 bucket get the auth tokens to impersonate anyone who has recently uploaded a file.

For me, headers in hooks would definitely be sufficient to handle this. I'll send auth tokens in the Authorization header the same way as my backend normally does and in my backend's webhook I'll take the token from the new headers object instead of the metadata object.

The only downside I thought of was that there might be a bunch of headers and not everyone may want all the unnecessary headers to be sent with every hook invocation. My idea was to add a `-hooks-headers` cli arg that can be used to tell tusd what headers to include in hooks.

e.g. `-hooks-headers=Authorization` for Bearer and http auth based auth and `-hooks-headers=Cookie` could be used for same-origin session based auth.

**Comment by Acconut** [comment]
This is currently being worked on. You can track the progress in https://github.com/tus/tusd/issues/212.

> The only downside I thought of was that there might be a bunch of headers and not everyone may want all the unnecessary headers to be sent with every hook invocation. My idea was to add a -hooks-headers cli arg that can be used to tell tusd what headers to include in hooks.

Interesting idea! However, I wouldn't add this in the first place and only later if people actually run into issues because too many headers are included.
