### ISSUE TITLE
Sends metrics to datadog

### ISSUE THREAD

**Issue by gottfrois** [tus/tusd#196]
Would be nice to add a way to configure Datadog APM to send metrics to.

https://app.datadoghq.com/apm/install#

```go
package main

import (
	"net/http"

	muxtrace "gopkg.in/DataDog/dd-trace-go.v1/contrib/gorilla/mux"
)

func main() {
	// Create a traced mux router.
	mux := muxtrace.NewRouter(muxtrace.WithServiceName("my-web-app"))

	// Continue using the router as you normally would.
	mux.HandleFunc("/", func(w http.ResponseWriter, _ *http.Request) {
		w.Write([]byte("Hello World!\n"))
	})
	http.ListenAndServe(":8080", mux)
}
```

I'm not sure how this is possible as i'm not very confortable with Go at the moment, any tips?

**Comment by kvz** [comment]
How about a separate script that scrapes /metrics and sends them to datadog?

**Comment by gottfrois** [comment]
I actually came across this in the meantime, i think this could be the best of both world, what do you think? https://www.datadoghq.com/blog/monitor-prometheus-metrics/

**Comment by kvz** [comment]
Yes, then we don't need to have any imperative binding with a commercial service (outside of maybe the building blocks of s3/gcloud buckets). 

You can see an example here: https://master.tus.io/metrics. You can monitor `/metrics` on your own instances just as well. 

The only thing we still need to do is make it fully compatible with prometheus. Currently we have spaces in a few keys which is not allowed. I think we should move to error constants instead of descriptions there.

**Comment by Acconut** [comment]
As @kvz said, we would like to avoid directly integrating with any third-party monitoring service. That being mentioned, the link to Datadog's blog looks like the best approach.

**Comment by gottfrois** [comment]
Sounds great guys 👍
