### ISSUE TITLE
always encounter 423 error

### ISSUE THREAD

**Issue by zhangalex** [tus/tusd#208]
Is there anyone can tell me why frequently encounter 423 error when a video player to grab video from the server.  The mp4 video should be like this https://tusd.domain.com/files/9296c3f2e3a699f90637a45495c206db

I can make sure that this file already uploaded completed. It can be accessible after you wait for some minutes, but sometimes it encounters 423 again.

**Comment by Acconut** [comment]
tusd currently does not allow concurrent access to uploads in order to avoid data loss if multiple clients are writing to the same file. This means that only one user can upload to/download from one upload resource at a given time, causing the 423 Locked errors that you are likely seeing.

The solution for now is to not use tusd for downloading videos (tusd is also not meant for this) but instead serve the files from your underlying data storage instead, whether it be the disk or on S3.

Does this make sense?

**Comment by zhangalex** [comment]
No thread to write the file. Only read the file. So, I think maybe it's sth wrong?

**Comment by Acconut** [comment]
It does not matter if someone "writes" to the file. Parallel reads are currently also not allowed. This is not misbehaving but we might reconsider this design decision.

**Comment by Acconut** [comment]
Yes, there are. As I said before in a comment, you should not use tusd for downloading files and instead serve the files from your storage directly. If you are using AWS S3 or Google Cloud Storage, download the files from the buckets directly. If you are using the (default) disk storage, you may use Nginx/Apache/HAProxy to serve the files directly from disk. All of these tools have better support for reading files and offer superior download performance than tusd can. Does that make sense to you?

**Comment by zhangalex** [comment]
Thanks
