### ISSUE TITLE
What is the right way to upload a folder?

### ISSUE THREAD

**Issue by yangyadi1993** [tus/tusd#217]
I don't know if this is the right place to ask. If it is not, forgive me. As far as I know, currently tusd and tus clients don't support folder upload. We have a use case to upload folders. So what should be a good solution? Upload a tar file and use the hook to decompress it or just call the upload function recursively?

**Comment by Acconut** [comment]
> I don't know if this is the right place to ask. If it is not, forgive me.

No worries, you're right. This is the best place to ask those questions.

> So what should be a good solution?

That's an interesting question, we never had this use case before. However, from my experience you may want to try uploading each file individually. This saves you from the overhead of packing and unpacking the individual files into an archive (e.g. tar, as you mentioned). It also allows you to already processing incoming files while other files are still being uploading. Furthermore, it's also easier to fully utilize the available bandwidth if you have multiple concurrent uploads running.

The only situation where I would advise you against this solution is when you have thousands of small files. In this case an archive may be faster since tusd has an overhead for creating uploads. But I am not sur if that's your use case.

**Comment by yangyadi1993** [comment]
Thank you very much for answering! That helped a lot.

**Comment by Acconut** [comment]
You're welcome. I will close this for now but feel free to open another issue if you have more questions :)
