### ISSUE TITLE
cli: UploadDir/S3 check has no effect

### ISSUE THREAD

**Issue by whs** [tus/tusd#229]
This line

https://github.com/tus/tusd/blob/33d12533e79db367bbd432ad912b84b0bdd4ce32/cmd/tusd/cli/flags.go#L69

doesn't do anything because `-dir` (`Flags.UploadDir`) has default value of `./data`.

I suggest either

- Remove this check entirely and preserve the current behavior of starting with no configuration required
- Set default value of `-dir` to empty string to make the check work
   - The check will also need `&& Flags.GCSBucket == ""` as well in this case otherwise GCS user won't be able to start server without dummy `-dir`

**Comment by Acconut** [comment]
Good point. I am not sure if this condition is useless since you may still be able to set `-dir` to an empty string on the command line. However, I agree with you that this check needs to be revisited. It would likely make more sense to move it to https://github.com/tus/tusd/blob/33d12533e79db367bbd432ad912b84b0bdd4ce32/cmd/tusd/cli/composer.go#L20 where we already inspect the different storage flags.
