### ISSUE TITLE
DynamoDB Locker: Advice on whether to upstream?

### ISSUE THREAD

**Issue by chen-anders** [tus/tusd#258]
We've switched away from operating an etcd3 locker to using a AWS DynamoDB locker to reduce costs/operational burden. Currently this code exists in its own repository (https://github.com/chen-anders/tusd-dynamo-locker) and I'm not exactly sure whether/how it should be upstreamed given the presence of a `setup` binary that is used for provisioning the DynamoDB table required for the locker. 

Please advise.

**Comment by Acconut** [comment]
Thank you for creating a DynamoDB locker package, that's amazing! First of all, I would like to say that my following response is just a collection of thoughts and those are not settled in stone. So feel free to discuss with us.

On one hand, it makes sense to keep much of the code in one repository to ensure all interfaces are compatible to each other. It also allows bigger refactoring to occur and helps maintaining a consistent level of quality. For example, if we find a problem with the S3 Store we can directly look if the GCS Store is also affected by the same issue and fix it before it turns into a real problem for the users. One codebase also allows us to easily integrate the DynamoDB locker into the `tusd` binary, so users can easily consume this service.

On the other hand, it also increases the code size and surface area of tusd significantly. This makes the tusd project more heavyweight and reduces our agility (for example, we tried to move to Go Modules for dependency management but we failed since big dependencies, such as etcd3, did not support Go Modules properly yet). Furthermore, we like to provide helpful support to our users. While we are not experts at using AWS S3, for example, it is usually necessary to have a basic understanding of the third-party service if we want to support a package depending on this external service. I, personally, don't have any experience with DynamoDB and also no resources at my hand to obtain the required experience. 

You see, I am not much concerned about the `setup` binary but rather the implication on the project by including another big feature. I also don't have a list of criteria which guarantee such a pull request would be accepted. My decision would also be influenced by whether you are able and willing to help us maintain and support a DynamoDB locker in the long term.

**Comment by chen-anders** [comment]
Thanks for the response (and apologies for my late response)!

> For example, we tried to move to Go Modules for dependency management but we failed since big dependencies, such as etcd3, did not support Go Modules properly yet

We ran into a similar issue with the etcd3 repository and go modules. I'd be happy to pull etcd3 locker out of this repository into its own separate repository with its own Travis CI runs, such that only the etcd3-tusd users have to worry about resolving the required dependencies to run the locker (since it is presumed that whoever uses it has some pre-requisite domain knowledge involved in troubleshooting such issues). 

We've been running the tusd dyamodb locker (after switching from the etcd3 locker for operational ease / reduce costs) for over a month now with no issues. I think @acj and I would be happy to keep it maintained in its own separate repository as well if it helps with containing the surface area of the tusd main repo (therefore making your life easier as well). 

My only ask would be to include links to the repos of both lockers in the README. Users who do have issues can file issues in the respective locker repository. 

How does that sound?

**Comment by Acconut** [comment]
That sounds all amazing, thank you for your offer! I believe that the community will benefit enormously from a more decentralized development of tusd and a direct way of contacting the maintainers.

We are happy to add links to tusd's README for any module that extends tusd or implements its interfaces. Moving etcd3locker into a separate package also seems like a good plan. However, due to tusd's backwards compatibility promise we cannot simply remove this package. Instead, I think we should deprecate it once the new repository is available and then remove github.com/tus/tusd/etcd3locker once the next major release is cut (see https://github.com/tus/tusd/issues/212).

Do you think this is a good plan?

**Comment by chen-anders** [comment]
That plan works for me!

**Comment by Acconut** [comment]
Perfect, let me know if there are any projects I should add to tusd's README and I am happy to do so!
