### ISSUE TITLE
Tus-Resumable present in OPTIONS request

### ISSUE THREAD

**Issue by alucic** [tus/tusd#260]
https://tus.io/protocols/resumable-upload.html#tus-resumable
>The Tus-Resumable header MUST be included in every request and response except for OPTIONS requests. The value MUST be the version of the protocol used by the Client or the Server.

>If the the version specified by the Client is not supported by the Server, it MUST respond with the 412 Precondition Failed status and MUST include the Tus-Version header into the response. In addition, the Server MUST NOT process the request.

If I'm not reading this wrong, `Tus-Resumable` should not be present in `OPTIONS` request and from what I'm reading it is right now.

https://github.com/tus/tusd/blob/25f64ee00a22b0a078e9bcffea3d0085389b8d4d/unrouted_handler.go#L191-L199

**Comment by Acconut** [comment]
You are reading everything correct but only missing one point. Your quote from the specification requires that every request and response must contain the Tus-Resumable header with the only exception being the OPTIONS *request*. However, this sentence does not exclude the *response* for an OPTIONS request from the rule. This response must, just as every other response, contain the Tus-Resumable header. Therefore, tusd is conformant to the specification.

To make it easier for you, let me explain the reasoning behind these decisions. The OPTIONS response includes the Tus-Resumable header, so clients can figure out what tus version a server is supported. The OPTIONS request does not contain the Tus-Resumable header, so that the client can get basic information about the server (such as the supported versions) regardless of what tus version the client supports.

**Comment by alucic** [comment]
You're right, Example for `OPTIONS` response holds `Tus-Resumable`
https://tus.io/protocols/resumable-upload.html#options

This PHP implementation is excluding `Tus-Resumable` from `OPTIONS` response and that's what caught me off guard
https://github.com/ankitpokhrel/tus-php/blob/1c36d2d542d848036c6e1fe85e8e1bb22f64833a/src/Middleware/GlobalHeaders.php#L21-L23

Thanks!

Closing this
