### ISSUE TITLE
Should give up firing hooks if file hook returns specific exit code (plus something similar for http hooks)

### ISSUE THREAD

**Issue by tim-kos** [tus/tusd#269]
**Is your feature request related to a problem? Please describe.**
At transloadit tusd sends progress reports to underlying Assemblies via the post-receive hook. However, if the underlying Assembly was cancelled or request-aborted, we have no way to communicate this back to tusd. Tusd will continue to hammer us with curl requests (that's what we do in the post-receive hook) about progress updates (in case the upload continues somehow or wasn't cancelled within tusd).

This can sometimes go on for hours, draining resources on servers unnecessarily.

**Describe the solution you'd like**
We need a way to tell tusd that the underlying upload collection (or whatever) has been invalidated, and that we no longer want hooks fired for it.

**Describe alternatives you've considered**
- tusd having an http (or whatever) interface where we can invalidate/cancel uploads to prevent further hooks fired. But that just adds extra work. I think hooks returning a specific exit code would be a more elegant way to achieve this, though.

**Can you provide help with implementing this feature?**
Possibly.

**Additional context**
There is one hook fired per second per upload. In a multi-upload scenario (let's say a Transloadit Assembly with 50 files), up to 50 hooks are fired every second. This is a lot. Now, when they are fired unnecessarily, things are even worse.

See https://github.com/tus/tusd/issues/268

**Comment by Acconut** [comment]
Thanks for the detailed description. In short, I agree that an exit code from the hooks is an elegant solution. However, there are still some questions open.

> We need a way to tell tusd that the underlying upload collection (or whatever) has been invalidated, and that we no longer want hooks fired for it.

Ok, let's assume that the hook returns status code X and tusd wants to invalidate the upload. But what does "invalidate" mean exactly? Should the current PATCH request be just interrupted or should the upload resource also be completely removed, so that the upload cannot be resumed anymore?

Another problem is that, using your solution, we can communicate the assembly cancellation to tusd but from tusd it's hard to reach the client. If tusd interrupts the current upload request, most tus clients will automatically retry, so the Transloadit SDKs may need to be equipped with an additional functionality to check whether the assembly is cancelled since it's hard to communicate this over the tus protocol.

> tusd having an http (or whatever) interface where we can invalidate/cancel uploads to prevent further hooks fired. But that just adds extra work. I think hooks returning a specific exit code would be a more elegant way to achieve this, though.

I also first thought about this, especially since tus already has a HTTP endpoint for terminating an uploading using a DELETE request. However, this one is designed to delete uploads which are currently not running, so it doesn't properly work for our situation.
Furthermore, I believe that the "stop signal" should come from the upload itself (e.g. the hooks) and not from an external actor (e.g. a different HTTP request). This is similar to how many threading APIs don't allow you to cancel a thread from the outside and only allow cancellation from the thread's inside itself. Anyways, I agree with you that a HTTP endpoint is not optimal.

**Comment by Acconut** [comment]
On a technical side, it should be uncomplicated to stop an incoming PATCH request: https://stackoverflow.com/questions/26437536/in-go-how-do-i-close-a-long-running-read. It bigger challenge is to ensure that the post-receive hooks contain a proper reference to their uploads (maybe using a FileInfo#Terminate method?). Just thinking out loud here.
