### ISSUE TITLE
add gRPC hooks

### ISSUE THREAD

**Issue by inigohu** [tus/tusd#311]
**Is your feature request related to a problem? Please describe.**
Add gRPC hooks

**Describe the solution you'd like**
Just like the HTTP hooks, support gRPC+protobuf hooks

**Describe alternatives you've considered**

**Can you provide help with implementing this feature?**
I can try to create a PR with a proposal

**Additional context**
Nowadays gRPC is a protocol widely used in cloud services

**Comment by Acconut** [comment]
I can understand why gRPC is compelling but could you elaborate what the benefits over plain HTTP hooks is? I am very concerned about adding another large dependency and more complex code that we have to maintain in the future, so that's why I a bit hesitant on that topic.

**Comment by inigohu** [comment]
There are a lot of comparatives between REST and gRPC out there, but basically is to give the option to do the communication through gRPC instead of having to generate an endpoint in HTTP.

Here are some benefits of using gRPC:
- You can use protocol buffer for data serialization. This makes payloads faster, smaller and simpler. 
- It is also type-safe
- gRPC makes better use of HTTP/2
- etc.

**Comment by Acconut** [comment]
Frankly, I am not sure if the advantages of gRPC justify the additional complexity cost we would have in tusd. We have to be very careful about what features we add to tusd, since those cannot be removed without breaking stuff for some users. Because of that, I am not entirely convinced yet that gRPC is a good fit for tusd since the HTTP hocks also support HTTP/2.

That being said, we're to explore it if you would be able to open a PR for it!
