### ISSUE TITLE
`post-finish` hook called before concat operation completed

### ISSUE THREAD

**Issue by gencer** [tus/tusd#321]
**Question**

I'm using `pre-create` and `post-finish` http-hooks. I've a mid-large sample file approx 1GB. I upload this using `Upload-Concat` and multi-threaded with `5`. Means I split it to chunks and upload 5 chunks at the same time.

Everything works until concat operation is finalized. When I mark upload as finished and send `POST+HEAD` to merge/concat uploaded parts to single file, it seems http-hook `post-finish` triggered before concat operation finishes.

In earlier days, I was using my own tus server which calculates `SHA256` and `CRC32` while uploading. Now I am doing this on ruby side when `post-finish` called. Because concat operation didn't finish, sha checksum gives incorrect output. It seems `post-finish` doesn't wait concat operation to completed.

Is it true? If so, either we need one more hook that notifies after concat or need to wait for concat before `post-finish`.

If you believe this is not the case just let me know i will dig into it more. I just can't find anything on my side maybe I miss something.

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Debian 10
- Used tusd version: 1.0.1
- Used tusd data storage: disk store
- Used tus client library: my own client :)

**Comment by gencer** [comment]
Nope!. My mistake. I was wrong its called in good order.

Closing this issue.

**Comment by gencer** [comment]
@Acconut just a question. Is there a specific reason why we do not remove chunks from disk when concat done?

When I upload a file in chunked mode, after concat request (POST+HEAD) both final file and cmall chunks exists at the same time.)

**Comment by Acconut** [comment]
> I've applied patches from older version. Now, tusd has internal hashing mechanism on-the-fly.

Not sure what you are referring to here, but tusd has no hashing functionality, such as SHA or CRC, built in.

> Is there a specific reason why we do not remove chunks from disk when concat done?

Yes, a partial uploads (that's what the tus-specific term for your chunk is) may be used for multiple concatenations, so we simply cannot remove them by default. Concatenation can be used for more than just parallel uploads, so that's why this rule exists.

> concat request (POST+HEAD)

FYI, the Concatenation request is done by the POST request. The HEAD request is not necessarily, unless you want to fetch additional data or so.
