### ISSUE TITLE
Using GCS through their S3 APIs

### ISSUE THREAD

**Issue by perbu** [tus/tusd#322]
**Is your feature request related to a problem? Please describe.**

I'm building an application that is platform-agnostic. The idea is to have the same application running on different clouds or local infra. tusd is one of several components. Each components gets S3 keys to get access to the objectstore.

Ideally I'd like to have the same environment settings on all clouds. This works for every component except tusd, which doesn't seem to work against GCS when using their S3 API.

tusd throws the following error when asked to use GCS through S3:
```
[tusd] 2019/11/04 14:05:56 event="ResponseOutgoing" status="500" method="POST" path="" error="s3store: unable to create multipart upload:
InvalidArgument: Invalid argument.
	status code: 400, request id: , host id: " 
```

**Describe the solution you'd like**
I would like tusd to work reliably against GCS using the S3 API.

**Describe alternatives you've considered**
I'm currently using a different container on Google Cloud than on other platforms.

**Can you provide help with implementing this feature?**
Yes. If this would something that would be of value to the project I could try to implement this myself and submit it. I might need a bit of guidance, however. I've never done serious Golang development.

**Additional context**
Thanks for creating a really useful project.

**Comment by Acconut** [comment]
> Thanks for creating a really useful project.

Thank you for the kind words :)

> I would like tusd to work reliably against GCS using the S3 API.

tusd has been successfully tested against other S3-compatible APIs, e.g. Minio or DigitalOcean storage, but never GCS. Frankly, it's the first time I hear that GCS has a S3-compatible interface. If it's possible that we also support GCS' S3 API without a high technical cost, I am more than happy to accept a patch.

Unfortunately, the error message is rather brief but I found reports of similar errors: https://blog.bandhosting.nl/blog/avoid-listobjects-invalid-query-parameter-s-encoding-type-errors-when-using-s3-with-google-cloud-storage

> If this would something that would be of value to the project I could try to implement this myself and submit it. I might need a bit of guidance, however. I've never done serious Golang development.

It would be amazing if you could have a look. Due to time restrictions, I won't be able to take a deep dive on my own in the near future. For your interest, the relevant code section for creating uploads using the S3 store is here: https://github.com/tus/tusd/blob/e138fc3e9e01ab8294a393ec0407eff38a708ddb/pkg/s3store/s3store.go#L181-L230

**Comment by perbu** [comment]
Thanks Marius. This is helpful.

If I get the time and cognitive capacity a PR will show up at a later stage. It might take a while so you might wanna close the issue (I don't know how you feel about having these open issues over a long time without a concrete roadmap to close).

**Comment by Acconut** [comment]
Sounds good, @perbu! I'll close this issue for now, but feel free to comment again whenever needed.

**Comment by skulltech** [comment]
I have the same need, I'm making a platform agnostic app, and `tusd` is unable to use the s3 compatible API of google cloud storage. Below are the logs I got from tusd

```
2025/02/25 14:55:42.567216 level=ERROR event=InternalServerError method=POST path="" requestId="" message="s3store: unable to create multipart upload:\noperation error S3: CreateMultipartUpload, https response error StatusCode: 403, RequestID: , HostID: , api error SignatureDoesNotMatch: Access denied."
2025/02/25 14:55:42.567248 level=INFO event=ResponseOutgoing method=POST path="" requestId="" status=500 body="ERR_INTERNAL_SERVER_ERROR: s3store: unable to create multipart upload:\noperation error S3: CreateMultipartUpload, https response error StatusCode: 403, RequestID: , HostID: , api error SignatureDoesNotMatch: Access denied.\n"
```

@perbu @Acconut were you guys able to solve for this?

**Comment by perbu** [comment]
It's been a long time since I worked with this. Since last time I worked with this I've heard that GCS is much closer aligned with S3 than was the case in 2019.  The log lines are a bit confusing, though, as there is no path or requestId allocated, which doesn't make sense in my head. 

Other than that, I have nothing to add. This question is no longer relevant for me. Good luck, I suggest debugging this a bit more and opening up a new issue if it doesn't start making sense.
