### ISSUE TITLE
Publish a helm chart for Kubernetes installation

### ISSUE THREAD

**Issue by sagikazarmark** [tus/tusd#324]
Are you planning to publish a helm chart for Tusd?

I'd be happy to create one for the project.

For a fully functioning helm chart you would also need a chart repository. If you are up for running one for yourself, then [ChartMuseum](https://chartmuseum.com/) is the official repository implementation. Otherwise I would humbly suggest using a hosted service published by Banzai Cloud (the company I work for): https://charts.banzaicloud.io/

As a last resort, I can offer hosting the chart in our chart repository: https://github.com/banzaicloud/banzai-charts

We have several third party projects hosting their charts there (like Cadence and Pomerium). (That would also have the advantage of appearing on [Helm Hub](https://hub.helm.sh/))

One last concern regarding helm charts is releasing them. Helm charts are usually versioned independently from the main application. That means you either create a separate repo for charts and version them there or introduce a versioning schema, like `chart/tusd/0.1.0` (and handle tags conditionally in CI).

Let me know what works for you.

**Comment by Acconut** [comment]
To be frank, I have never used Helm before and it's the first time I have heard of Helm Charts, so I am not sure what benefits they provide or what makes it actually different than the Docker image.

However, since our core teams is not very experienced using these technologies, I don't think it's a great idea that we host it ourselves, but instead let the community fill in that gap. We would appreciate it a lot if you could take care of that, as you mentioned :)

**Comment by sagikazarmark** [comment]
Helm Chart is basically a "package" for Kubernetes manifests. It's not a container image, rather the deployment "scripts" to run that image in Kubernetes.

At it's core a Helm Chart is a set of templates and default values which you. can change to generate different Kubernetes manifests.

I'll come up with something then and post updates here.

**Comment by Acconut** [comment]
> I'll come up with something then and post updates here.

Sure, looking forward to hearing from you :+1:

**Comment by renepardon** [comment]
If you have something already that would be nice. Otherwise I’ll just create one by myself with helm
create command.

Von unterwegs gesendet

Am 30.03.2021 um 15:38 schrieb Márk Sági-Kazár ***@***.***>:

﻿

Yeah, I totally forgot about it. 😄 I can probably come up with something during the weekend if you need a chart.

**Comment by sagikazarmark** [comment]
@renepardon Here is an initial version: https://github.com/sagikazarmark/helm-charts/tree/master/charts/tusd

I'll make some changes around configuration to make it more safe, but it's a start: https://github.com/sagikazarmark/helm-charts/issues?q=is%3Aissue+is%3Aopen+label%3Acharts%2Ftusd

**Comment by renepardon** [comment]
@sagikazarmark looks a bit better than the default output of _helm create_ 👍🏼

**Comment by sagikazarmark** [comment]
I think this is basically done. There is room for improvement, but the chart is functional and allows turning all the knobs of tusd.

Feel free to open issues: https://github.com/sagikazarmark/helm-charts/issues

Or send PRs for existing ones: https://github.com/sagikazarmark/helm-charts/issues?q=is%3Aissue+is%3Aopen+label%3Acharts%2Ftusd

@Acconut let me know if you want me to send a PR to the documentation linking this chart.

**Comment by Acconut** [comment]
> @Acconut let me know if you want me to send a PR to the documentation linking this chart.

Yes, that would be amazing and help others find this incredible resource as well! :100:

**Comment by sagikazarmark** [comment]
@Acconut #475
