### ISSUE TITLE
How to set response header http to https

### ISSUE THREAD

**Issue by arck123** [tus/tusd#329]
how to set location in response header http to https ?

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux
- Used tusd version: lastest
- Used tusd data storage: Minio S3
- Used tusd configuration: 
- Used tus client library: tus-js-client

**Comment by arck123** [comment]
![rh](https://user-images.githubusercontent.com/18304433/69800704-ca530000-11a3-11ea-9f51-d9c43b681810.jpeg)

**Comment by Acconut** [comment]
Please read the documentation before opening a ticket: https://github.com/tus/tusd/blob/master/docs/faq.md#how-can-i-access-tusd-using-https

**Comment by genseirin** [comment]
I came across this issue with the same question and don't see how the provided link answers it. The mentioned FAQ and [docs](https://github.com/tus/tusd/blob/main/docs/_getting-started/configuration.md#httpstls) describe how requests and responses can be served over TLS. I understood the question more like how to change the protocol in the URL of the "Location" to "https://", in order to avoid having to redirect all incoming PATCH requests.
Anyway, not a big issue, redirecting will get the job done. 😃
