### ISSUE TITLE
Can't trigger post-finish hook when using Upload-Defer-Length at creation stage

### ISSUE THREAD

**Issue by djbloc** [tus/tusd#394]
The protocol documentation doesn't state a way for a client to trigger the "post-finish" event if the upload length is not known at creation with the Upload-Defer-Length header.

For scenarios where the upload length is not known at creation then I would expect the client can signal to tusd the upload has completed which in turn would trigger the "post-finish" hook. This could either be with a header in the final PATCH chunk or alternately a stand-alone POST call.

**Comment by Acconut** [comment]
> For scenarios where the upload length is not known at creation then I would expect the client can signal to tusd the upload has completed which in turn would trigger the "post-finish" hook.

Such a mechanism already exists. When the client knows the file's length (e.g. because all data has been uploaded to the tusd server), the client includes the Upload-Length header in a PATCH request. Therefore, the server knows when the upload is complete and can then trigger the post-finish hook accordingly.

Does this not work for you?

**Comment by djbloc** [comment]
I must have read the protocol docs numerous times but it obviously didn't stand out for me...

> Once it is known the Client MUST set the Upload-Length header in the next PATCH request.

Apologies, it does work when adding Upload-Length header to the final patch.
