### ISSUE TITLE
Blocking file hooks send clients more than hook output.

### ISSUE THREAD

**Issue by ZenOgre** [tus/tusd#405]
I'm using the pre-create file hook to prevent unauthorized uploads. When using a non zero exit to block the upload I expected the hook's output to be sent to the client by itself. Instead an extra line about the hook execution is being added at the top of the output as shown here. 

```
pre-create hook failed: exit status 1
(the actual hook output)...
```

I can of course strip the extra line off before parsing it on the client side as JSON but it seems like this data probably shouldn't be being sent to the client.

**Comment by Acconut** [comment]
Thank you for reporting this. Right now, this is the expected behavior. The additional output is intended to help developers figure out why the request has failed. I am currently thinking about a new hook interface which would remove this additional line. As far as I can understand, this is not a blocking issue for you?

**Comment by ZenOgre** [comment]
That's correct, not a problem at all. I was able to work around it by removing the line at the client. I was just surprised to see it there and thought it may have been unintentional.  I'll keep an eye out for future updates to the hook system. Thanks!
