### ISSUE TITLE
only .info is getting uploaded

### ISSUE THREAD

**Issue by Neha-Prabhu** [tus/tusd#438]
I want to upload vidoes/images via tusd to S3 but I am not able find perfect resources to do the same
with all the knowledge I gathered this is what I could come up with :

```
import (
	"fmt"
	"net/http"
	"regexp"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"

	"github.com/tus/tusd/pkg/filestore"
	tusd "github.com/tus/tusd/pkg/handler"
	s3store "github.com/tus/tusd/pkg/s3store"
)
func main() {

	store := filestore.FileStore{
		Path: "./uploads",
	}

	S3_ACCESS_KEY := "***"   // replacing the access key here while testing
	S3_SECRET_KEY := "***"
	s3Config := &aws.Config{
		Region:      aws.String("ap-south-1"),
		Credentials: credentials.NewStaticCredentials(S3_ACCESS_KEY, S3_SECRET_KEY, ""),
	}
	s3Locker := s3store.New("***", s3.New(session.Must(session.NewSession()), s3Config))

        // I dont know what the below line does and is it necessary? If yes can u elaborate?
	var finisherDataStore tusd.FinisherDataStore = controllers.FinisherDataStore{
		Store: store,
	}


	composer := tusd.NewStoreComposer()

	s3Locker.UseIn(composer)

	handler, err := tusd.NewHandler(tusd.Config{
		BasePath:                "/videos/",
		StoreComposer:           composer,
		NotifyCompleteUploads:   true,
		NotifyTerminatedUploads: true,
		NotifyUploadProgress:    true,
		NotifyCreatedUploads:    true,
	})
	if err != nil {
		panic(fmt.Errorf("Unable to create handler: %s", err))
	}
	http.Handle("/videos/", http.StripPrefix("/videos/", handler))
	err = http.ListenAndServe(":8080", nil)
	if err != nil {
		panic(fmt.Errorf("Unable to listen: %s", err))
	}
}

```

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux
- Used tusd version: current
- Used tusd data storage: s3
- Used tusd configuration: did not understand this question. just running the file using go run server.go
- Used tus client library: Uppy.js

Am I missing something?

**Comment by fortunto2** [comment]
Hmm... same error but for Google Cloud storage

used to work well locally, tried to transfer it to the cloud today and also a problem

**Comment by Acconut** [comment]
@Neha-Prabhu You are enabling all the events, e.g. `NotifyCompleteUploads`, but are not listening for the events on the channels (e.g. https://github.com/tus/tusd/blob/0822c0ac436c7c6d6d320879ec50758b430494df/pkg/handler/unrouted_handler.go#L128). Since the channels are not buffered, it will cause tusd to hang and therefore no actual file data is stored on S3. You must either listen for events on the channels (see https://github.com/tus/tusd/blob/0822c0ac436c7c6d6d320879ec50758b430494df/cmd/tusd/cli/hooks.go#L106-L121) or you must disable all `Notify*` options.

@fortunto2 Please open a new issue and include more details.

**Comment by Neha-Prabhu** [comment]
got it. Thank you.
