### ISSUE TITLE
html video play controls from tusd url

### ISSUE THREAD

**Issue by benitogf** [tus/tusd#449]
**Question**

Using tusd urls as a source for html video?

It works for mp4 files by adding the type attribute:

```
<video preload="auto"
                controls
                src={tusdVideoFileURL}
                type='video/mp4'></video>
```

but the timeline control doesn't work, could this be missing metadata in the file that is on the .info?

I would like to make the timeline controls work if anyone has succeeded at this advice would be much appreciated, will keep trying on my end and keep this updated

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Windows
- Used tusd version: v1.4.0
- Used tusd data storage: disk store
- Used tusd configuration: none
- Used tus client library: tus-js-client

**Comment by Acconut** [comment]
tusd supports GET requests but does not support the `Range` header in GET requests which is used by video players to seek to certain time stamps. We currently have no intention of implementing support for this feature since tusd is not meant to be used as a file server. Instead, it is best to use a proper tool like nginx for this.

**Comment by benitogf** [comment]
how can I make nginx serve the video files with `Range` header support? Will look into it, thanks @Acconut

**Comment by Acconut** [comment]
I think nginx supports it by default and there is no additional option required to enable the Range header, as far as I know.
