### ISSUE TITLE
Why lock all the time in GetFile

### ISSUE THREAD

**Issue by bluven** [tus/tusd#466]
**Question**

I can understand we need to lock when uploading or deleting to avoid contention, but dont' quite understand why lock all the time during downloading a file?

```
if handler.composer.UsesLocker {
  lock, err := handler.lockUpload(id)
  if err != nil {
	handler.sendError(w, r, err)
	return
  }
  defer lock.Unlock()
}
```
This make concurrent file downloading impossible.

```
wget http://localhost:18080/files/07c2d764b185546a953ed60d56dff40f+2~DoMdYaSLToQlSpT9H30nGOrkxcabHCd
--2021-03-19 10:14:44--  http://localhost:18080/files/07c2d764b185546a953ed60d56dff40f+2~DoMdYaSLToQlSpT9H30nGOrkxcabHCd
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:18080... connected.
HTTP request sent, awaiting response... 423 Locked
2021-03-19 10:14:44 ERROR 423: Locked.
```

**Comment by Acconut** [comment]
The lock is necessary to prevent a download while the file is being uploaded (i.e. a PATCH request is currently active). We could use read/write lock to allow concurrent read but only exclusive writes but our current lock mechanism does not support that. All in all, this is not a priority for us since tusd is not designed for serving content but for file uploads. The GET endpoint is only there for testing and ease of use, but not for production use.
