### ISSUE TITLE
Changing GCS/S3 prefix with pre-create.

### ISSUE THREAD

**Issue by mlnj** [tus/tusd#488]
**Question**
Is it possible to decide a prefix for a file on the pre-create hook?

Using Uppy.js with tusd docker containers to upload to Google Storage or S3. 
Trying to save files into a structure like: 

`<bucket>/<uuid>/<file>`

**Setup details**
Please provide following details, if applicable to your situation:

    Operating System: Linux
    Used tusd version: latest docker (sha256:8fd45989c674d3cb919c1bcfc7f3096bf98c14684885df546166ea04aae6b0ce)
    Used tusd data storage: Ggoogle Storage
    Used tusd configuration: [gcs-bucket test_bucket, -hooks-enabled-events]
    Used tus client library: uppy.js

**Comment by Acconut** [comment]
No, this is unfortunately currently not possible. The prefix (or destination path) cannot be influenced by the pre-create hook (for any kind of storage inside tusd). We are considering adding such a functionality in the future since some people ask for it, but we have no plans for that in the near future.

**Comment by Akkarine** [comment]
It would be useful for cases, when you serve uploaded files not through tusd, but with S3 with CDN.

**Comment by Acconut** [comment]
I can see how this would be useful but we still do not have any plans to implement this on our own. We are open to PRs but this is not priority. If you want a per-upload prefix for the objects on GCS/S3, you can rename/move the object on the cloud storage once the upload is completed.
