### ISSUE TITLE
Configuration using environment variables

### ISSUE THREAD

**Issue by meidlinga** [tus/tusd#659]
**Is your feature request related to a problem? Please describe.**
In modern containerized environments things tend to be easier when the application is configurable via environment variables.

**Describe the solution you'd like**
I would like to configure all the things configurable using flags, also by enviroment varables. They should have the same naming with a prefix. e.g.: `-azure-storage` becomes `TUSD_AZURE_STORAGE`, `-port` becomes `TUSD_PORT`.

**Describe alternatives you've considered**
As a workaround I built a dedicated container, building a startup command with cli options concatinated based on enviroment variables.

**Can you provide help with implementing this feature?**
Yes

**Additional context**
My suggestion would be using https://github.com/jnovack/flag which is a compatible replacement for the currently used flag package. Using this package the goal can be achived with relatively low effort.

**Comment by Acconut** [comment]
To be honest, I am not very much sold on this idea. I like that tusd has only one way to be configured and not multiple approaches, i.e. command line, config file and environment variables. This adds complexity to the user and can cause confusion when an environment variables is overwritten by a command line arguments. Since you already found a solution to your situation, I don't think it is likely that tusd will offer configuration using environment variables soon, unless many users share your request :)
