### ISSUE TITLE
Resume capability for HTTP GET 

### ISSUE THREAD

**Issue by Arman92** [tus/tusd#67]
It seams that tusd does not support "**Range**" headers for resuming interrupted downloads, or using a download manager to faster download the files.

It would be very nice to have this feature ;-)

**Comment by Acconut** [comment]
Even if downloading content is not the scope of the tus protocol, I do see the reasons for why the tusd should server should support range requests. Luckily, Golang includes a convenient function for serving content over HTTP (https://golang.org/pkg/net/http/#ServeContent) which also respects the Range header.
Unfortunately, due to it's argument types, this method may only be useful if you are using a disk-based storage (the stream needs to support seeking which is only efficient for disk-based storages in our case). Considering this limitation, would you still benefit from this feature addition?

**Comment by Arman92** [comment]
I don't understand what you mean of "Disk-based storage", what other options for file storage do you have in mind?

**Comment by Acconut** [comment]
I agree that my description was not accurate enough. What I meant was local disk-based storage where the tus server writes the uploads directly to a local disk (in theory, it could also be a mounted network file system; the server just needs to be able to access the files using standard file system methods). The opposite of this would be storing the uploads on a remote server, e.g. AWS S3 or any other cloud provider. The difference is that in latter case you do not have direct access to the files but instead needs to use their provided API.

**Comment by Arman92** [comment]
Yes I understand, we intend to use our own storage for file saving, if you suggest to use another http server, say Apache, how do we know the remote file URL in clients? would it be sufficient to just convert the resolved url (the url that tus gives when starting to upload a file) to something that our http server understands?

**Comment by Acconut** [comment]
If you want to run a proxy in front of a tusd server, be sure to add the `-behind-proxy` flag to the command line (or use `RespectForwardedHeaders` in https://godoc.org/github.com/tus/tusd#Config if you use the package directly). When enabled and assuming your proxy sends the X-Forwarded-* or Forwarded headers, the URL returned after creating an upload will automatically use the host, port and protocol from the proxy. In most cases, this should be enough to run tusd behind Apache, Nginx etc. You don't have to do any URL conversion manually.
