### ISSUE TITLE
Broken compatibility for PATCH request to file that can't be found

### ISSUE THREAD

**Issue by ChrisSchinnerl** [tus/tusd#707]
**Describe the bug**
We recently upgraded our dependency from tusd v1.6.0 to v1.9.0 and it seems like the status code returned by a `PATCH` for a file that doesn't exist now returns a 500 instead of a 404 even though we are returning a `os.ErrNotExist` in our implementation of the data store interface. That's a bit unexpected for a non-breaking version upgrade.

To mitigate this we changed the code to returning `handler.ErrNotFound` which I suppose is the new/preferred way?

**To Reproduce**

Implement the data store interface and return a `os.ErrNotExist` in `GetUpload`.

**Expected behavior**
A 404 is returned 

Seems like the `UnroutedHandler` is missing the `os.IsNotExist` check at the beginning of `sendError` now that it had in 1.6.0.

**Comment by Acconut** [comment]
> To mitigate this we changed the code to returning `handler.ErrNotFound` which I suppose is the new/preferred way?

Yes. this is the correct approach. We consider the previous interpretation of `os.ErrNotExist` as `handler.ErrNotFound` a bug and therefore removed it. The problem is that not every `os.ErrNotExist` error should be interpreted as an upload that is not found. Image that your data storage is trying to access a temporary file for saving the uploaded data. If that file somehow gets removed during that process and you get an `os.ErrNotExists`, you want that error to be causing a 500 response and not a 404. That's the motivation behind this change. I hope it makes sense to you.
