### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by kevin-openc** [tus/tusd#75]
i am a newbie to tus (and github), hope to get a right place to ask.

i am trying to start a tusd on an aws ec2 instance and client on my local computer.i have tried to use the binary and everything all right. 

However, i would like to config the datastore path, so i used the sample code [here](https://github.com/tus/tusd#using-tusd-manually) and the below error occur,

> Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

checked i have to allow the access of the ec2 from other origin, but i am not sure how to achieve. thanks for any reply.

**Comment by Acconut** [comment]
tusd should usually set the Access-Control-Allow-Origin in the corresponding responses (see https://github.com/tus/tusd/blob/master/unrouted_handler.go#L136). However, a proxy which may be running in front of tusd could provide issues here. In order to help you, we would need a bit more details:

How does your exact setup on EC2 look like?
Which commands did you invoke to start tusd?
Under which URL is tusd available?
Does your client point to the correct URL for reaching your tusd server?
What does the complete error message say?

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)
