### ISSUE TITLE
Anyway to change the owner of uploaded files?

### ISSUE THREAD

**Issue by kevin-openc** [tus/tusd#82]
I know this may be a bit off-topic, but i have researched a lot and no clue.
The case is that I am working on a simple web application that allows people to upload files and edit them.
However I found that the uploaded files are owned as root and with permission 644, which cannot be edited by apache. 
I have no idea how to allow apache edit the file that is not owned by it. Is it possible to change the owner or permission once tusd received the file?
many thanks!

**Comment by Acconut** [comment]
> However I found that the uploaded files are owned as root

This indicates that you are running tusd under the root user which is generally not recommended because if the software contains a vulnerability which could be used for remote code execution, the attacker would gain root access. One approach is to run tusd with the same user as apache is running, so the files which are created for the uploads, will be owned by the apache user.

> Is it possible to change the owner or permission once tusd received the file?

Alternatively, you can use the undocumented hook feature. To do this create a file called `.hook/post-finish` with following content:

```bash
#!/usr/bin/env bash

user="USER_WHO_SHOULD_OWN_UPLOADS"
dir="PATH_TO_UPLOADS"
chown "$user" "${dir}/${TUS_ID}.bin"
```

Then execute tusd with the `--hook-dir=.hooks` flag and the uploaded files should now be owned be the specified user.

**Comment by kevin-openc** [comment]
thanks for your quick response!! since I am running the binary, I have choose to run the process by apache!!
many thanks!!!!
