### ISSUE TITLE
Disable dependabot in all Tus repos

### ISSUE THREAD

**Issue by jaime-rivas** [tus/tusd#865]
First congratulations to the whole tus team for this project, it's a great initiative. We are evaluating tus and tracking its progress, and it is not easy given the large number of dependabot commits that bump packages. It creates too much noise in the commit history and gets in the way to see the real progress of each repo. Probably you have reasons to keep it as is, but I wanted to open the question in case you might reconsider it. Thank you very much.

**Comment by Acconut** [comment]
I can understand your concerns, but dependabot provides unmeasurable value for us. Without it, dependency updates would be a big hassle and done very rarely due to the large friction. So, for now we prefer to keep using dependabot, even if it means a larger volume of commits. Maybe you are able to ignore these commits on your side.
