### ISSUE TITLE
`-hooks-http-forward-headers` is not respecting Host header.

### ISSUE THREAD

**Issue by brijsiyag** [tus/tusd#959]
**Question**
When I pass `Host` header in the `-hooks-http-forward-headers` list, it doesn't respect that and sets it to the host of `-hooks-http`. My application doesn't use `X-Forwarded-Host`. 

The behaviour be when we pass `Host` in `-hooks-http-forward-headers`, than do not set and pass the received header.

Is there any way to do this or I'm missing something ?

**Comment by Acconut** [comment]
I don't think it makes sense to forward the `Host` header using `-hooks-http-forward-headers`. It is relevant in order to perform the HTTP hook properly and thus is should not be modified by taking it from the client request. Similar arguments apply to headers like `Content-Length`, `Content-Type`, `Transfer-Encoding` etc.

If you want to access all headers from the client request, you can inspect the`HTTPRequest` property in the request body of the HTTP hook: https://github.com/tus/tusd/blob/main/docs/hooks.md#usage
