### ISSUE TITLE
version `GLIBC_2.32' not found (required by tusd)

### ISSUE THREAD

**Issue by brijsiyag** [tus/tusd#964]
**Describe the bug**
[tusd_liunx_amd64.tar.gz](https://github.com/tus/tusd/releases/download/v1.11.0/tusd_linux_amd64.tar.gz) binary is not working on Ubuntu20.04 or Debian11, It says 
```
tusd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by tusd)
tusd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by tusd)
```
But the [tusd_linux_386.tar.gz](https://github.com/tus/tusd/releases/download/v1.11.0/tusd_linux_386.tar.gz) binary is working fine on older versions of OS.
 
On Ubutnu22.04 or Debian12 all binaries works as expected. Also there is no problem with ARM binaries. 
> glibc is provided by the OS (Debian or Ubuntu). Typically, Linux binaries compiled on newer OS releases don’t run on older OS releases for that reason.

But I think we should support the recent older OS.

I tested which last version that not encounters this problem, found v1.10.0, this works fine on Ubuntu20.04 and Debian11.

**To Reproduce**
* Download v1.11.0 binary tusd_linux_amd64.tar.gz
* Run on a machine which have Ubuntu20.04 or Debian11 and x86_64 arch.

**Expected behavior**
Binaries should support older OS versions.

**Comment by Acconut** [comment]
This looks very similar to https://github.com/tus/tusd/issues/909. Can you please try out the solutions from there?

**Comment by brijsiyag** [comment]
We can't upgrade or downgrade glibc because we don't know what will break on that. 
The other option we are left with is do our own compilation, it will work surely but doing it on every upgrade of our app Zulip will be costly and also currently we don't want to add GO as dependency.

**Comment by Acconut** [comment]
I see. But I am not sure what we can do on our end to help with this. Do you have any idea?

**Comment by brijsiyag** [comment]
I'm not sure on which OS version you compiled the binaries, But I think compiling on a lower version should work on a latest version also. Did you use Ubuntu22 or Debian12 to compile binaries for v1.11.0? In case you remember which OS version you used for v1.10.0 because it works as expected, might help.

**Comment by brijsiyag** [comment]
Thanks @Acconut , Is there any specific reason for using latest one? Because it is restricting the recent older OS versions.

**Comment by brijsiyag** [comment]
I got a workaround for now, which is I forked the repo and did a fork release altering the `release.yml` file to use ubuntu-20.04 for binary building. In case someone wants to use that if they encounter similar thing, feel free to, Here is the link to the release - https://github.com/brijsiyag/tusd/releases/tag/v1.11.1 
Please note this is not an official release. 

Thanks a lot @Acconut for the information.

**Comment by Acconut** [comment]
> Is there any specific reason for using latest one?

I would like to keep using the latest image, yes. This way we do not have to worry about keeping the image up-to-date. Ideally, the OS that is used for cross-compilation should not influence the output binary, so changing the Ubuntu version is not the correct solution to this problem IMO.

I was wondering because at Transloadit, we also use tusd on Ubuntu 20.04 without issues. However, we are running tusd v2 in production already (the pre-releases), for which we disabled CGO (see https://github.com/tus/tusd/commit/edf8238af91b5c1ab56d6953078593c3e646bfaa). If I remember correctly, this ensures that the output binaries are statically linked and will not use libc at all. Hence, there can be no issues with glibc.

I would encourage you to also try v2 on your system and see if that helps. Maybe we can also incorporate that commit into tusd v1.

**Comment by brijsiyag** [comment]
> I would like to keep using the latest image, yes. This way we do not have to worry about keeping the image up-to-date.

Agree, wasn't a great question.

I tried [v2.0.0-rc19](https://github.com/tus/tusd/releases/tag/v2.0.0-rc19), seems working fine on Debian11.

> changing the Ubuntu version is not the correct solution to this problem IMO.

Yeah it is not, It is going to take time before we roll out chunk upload, So a release with CGO disabled commit will sure help if that works.

Off topic - If you are using v2 at Transloadit, will you recommend us using that in production? Because of lack of v2 features, we are doing some temporary work to get it done.

Thank you!!

**Comment by Acconut** [comment]
> Because of lack of v2 features, we are doing some temporary work to get it done.

If you are integrating tusd from scratch, I would recommend you to go with v2. Even though it is a pre-release, we use it in production without issues. There are no problems with stability, but documentation is still lacking and we might make some minor breaking changes. This is why the release is not yet complete. But building on v1 now does not make a lot of sense because v2 is be released in the next weeks and then we cannot develop v1 any further. So you would likely want to switch in the near future anyways.

**Comment by Acconut** [comment]
I think this can be closed now. tusd v2 has been released and its release binaries are compiled without CGO and thus should not cause this issue.
